site_name: 2204 Rambots Documentation

repo_name: frc2204/ramdocs
repo_url: https://github.com/frc2204/ramdocs

nav:
  - Home: index.md
  - Programming:
    - Programming Overview: programming/overview.md
    - Version Control:
        - Git Introduction: programming/version-control/git-intro.md
        - Git In Action (Single Repository): programming/version-control/git-in-action-single.md
        - Git In Action (Multiple Repositories): programming/version-control/git-in-action-multiple.md
        - Github: programming/version-control/github.md
        - Git Cheat Sheet: programming/version-control/git-cheat-sheet.md
        - Git WTFs: programming/version-control/git-wtfs.md
  - Electrical:
    - Electrical Overview: electrical/overview.md
    - Rev Robotics Diagram: electrical/electrical-rev-diagram.md
  - Design:
    - Design Overview: design/overview.md
  - Fabrication:
      - Fabrication Overview: fabrication/overview.md
      - Tools:
        - Power Drill: fabrication/tools/drill.md
        - Circular Saw: fabrication/tools/circular-saw.md
        - Drill Press: fabrication/tools/drill-press.md
        - Impact Driver: fabrication/tools/impact-driver.md
        - Miter Saw: fabrication/tools/miter-saw.md
  - Business:
    - Business Overview: business/overview.md


theme:
  name: material
  logo: assets/logo_42.png
  features:
    - navigation.tabs
    - navigation.expand
    - toc.follow
    - toc.integrate
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - social
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
     custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format