site_name: 2204 Rambots Documentation

repo_name: frc2204/ramdocs
repo_url: https://github.com/frc2204/ramdocs

edit_uri: edit/main/docs/

site_url: https://docs.rambots.org/
site_description: The official source of documentation and training materials for the 2204 Rambots
site_author: 2204 Rambots

copyright: '&copy; Copyright 2023 Rambots'

nav:
  - Home: index.md
  - Programming:
    - Programming Overview: programming/overview.md
    - Kotlin:
        - Fundamentals:
          - Introduction to Programming: programming/kotlin/fundamentals/intro-to-programming.md
          - Introduction to Kotlin: programming/kotlin/fundamentals/intro-to-kotlin.md
          - Variables: programming/kotlin/fundamentals/variables.md
          - Collections: programming/kotlin/fundamentals/collections.md
          - Control Flow: programming/kotlin/fundamentals/control-flow.md
          - Loops: programming/kotlin/fundamentals/loops.md
          - Functions: programming/kotlin/fundamentals/functions.md
          - Common Mistakes: programming/kotlin/fundamentals/common-mistakes.md
        - Object Oriented Programming:
          - Classes: programming/kotlin/oop/classes.md
          - Inheritance: programming/kotlin/oop/inheritance.md
          - Abstraction: programming/kotlin/oop/abstraction.md
          - Polymorphism: programming/kotlin/oop/polymorphism.md
          - Encapsulation: programming/kotlin/oop/encapsulation.md
          - Interfaces: programming/kotlin/oop/interfaces.md
          - Access Modifiers: programming/kotlin/oop/access-modifiers.md
          - Static vs. Instance: programming/kotlin/oop/static-vs-instance.md
          - Data Classes and Structures: programming/kotlin/oop/data-classes-and-structures.md
    - Version Control:
        - Git Introduction: programming/version-control/git-intro.md
        - Git In Action (Single Repository): programming/version-control/git-in-action-single.md
        - Git In Action (Multiple Repositories): programming/version-control/git-in-action-multiple.md
        - Github: programming/version-control/github.md
        - Pull Requests: programming/version-control/pull-requests.md
        - Git, GitHub, and IntelliJ: programming/version-control/git-github-intellij.md
        - Git Development Patterns: programming/version-control/git-dev-patterns.md
        - Git Practice Activity: programming/version-control/git-practice-activity.md
    - Advanced Topics:
        - PID Controllers: programming/advanced-topics/pid-control.md
        - Inverse Kinematics: programming/advanced-topics/inverse-kinematics.md
        - Motion Profiling: programming/advanced-topics/motion-profiling.md
        - Path Planning: programming/advanced-topics/path-planning.md
        - Vision Processing: programming/advanced-topics/vision-processing.md
        - Testing: programming/advanced-topics/testing.md
        - Debugging: programming/advanced-topics/debugging.md
        - Logging: programming/advanced-topics/logging.md
        - Unit Testing: programming/advanced-topics/unit-testing.md
        - Continuous Integration: programming/advanced-topics/continuous-integration.md
        - Continuous Deployment: programming/advanced-topics/continuous-deployment.md
  - Electrical:
    - Electrical Overview: electrical/overview.md
    - Safety:
      - Robot Interaction: electrical/safety/robot-interaction.md
      - Electrical Safety: electrical/safety/electrical-safety.md
    - Theoretical:
      - Voltage: electrical/theoretical/voltage.md
      - Current: electrical/theoretical/current.md
      - Resistance: electrical/theoretical/resistance.md
      - Wiring Gauges: electrical/theoretical/wiring-gauges.md
      - Ohm's Law: electrical/theoretical/ohms-law.md
      - Kirchhoff's Laws: electrical/theoretical/kirchhoffs-laws.md
      - Series Circuits: electrical/theoretical/series-circuits.md
      - Parallel Circuits: electrical/theoretical/parallel-circuits.md
      - Series-Parallel Circuits: electrical/theoretical/series-parallel-circuits.md
      - Capacitors: electrical/theoretical/capacitors.md
      - Inductors: electrical/theoretical/inductors.md
      - Transformers: electrical/theoretical/transformers.md
      - Diodes: electrical/theoretical/diodes.md
      - Microcontrollers: electrical/theoretical/microcontrollers.md
      - Microprocessors: electrical/theoretical/microprocessors.md
    - Systems:
      - Power Distribution: electrical/systems/power-distribution.md
      - CAN Bus: electrical/systems/can-bus.md
      - Pneumatics: electrical/systems/pneumatics.md
      - Sensors: electrical/systems/sensors.md
      - Electrical Diagrams: electrical/systems/electrical-diagrams.md
  - Design:
    - Design Overview: design/overview.md
  - Fabrication:
      - Fabrication Overview: fabrication/overview.md
      - Hand Tools:
          - Calipers: fabrication/hand-tools/calipers.md
          - Chain Breakers: fabrication/hand-tools/chain-breakers.md
          - Deburrers: fabrication/hand-tools/deburrers.md
          - Files: fabrication/hand-tools/files.md
          - Hack Saws: fabrication/hand-tools/hack-saws.md
          - Hammers: fabrication/hand-tools/hammer.md
          - Hand Saws: fabrication/hand-tools/hand-saws.md
          - Hex Keys: fabrication/hand-tools/hex-keys.md
          - Knives: fabrication/hand-tools/knives.md
          - Levels: fabrication/hand-tools/levels.md
          - Marking Tools: fabrication/hand-tools/marking-tools.md
          - Measuring Tools: fabrication/hand-tools/measuring-tools.md
          - Pliers: fabrication/hand-tools/pliers.md
          - Punches: fabrication/hand-tools/punches.md
          - Screwdrivers: fabrication/hand-tools/screwdriver.md
          - Sockets: fabrication/hand-tools/sockets.md
          - Squares: fabrication/hand-tools/squares.md
          - Vises: fabrication/hand-tools/vises.md
          - Wrenches: fabrication/hand-tools/wrench.md
      - Power Tools:
        - Power Drill: fabrication/power-tools/drills.md
        - Circular Saw: fabrication/power-tools/circular-saws.md
        - Drill Press: fabrication/power-tools/drill-presses.md
        - Impact Driver: fabrication/power-tools/impact-drivers.md
        - Miter Saw: fabrication/power-tools/miter-saws.md
      - Manufacturing:
          - Additive Manufacturing: fabrication/manufacturing/additive-manufacturing.md
          - Subtractive Manufacturing: fabrication/manufacturing/subtractive-manufacturing.md
          - 3D Printing: fabrication/manufacturing/3d-printer.md
          - Laser Cutting: fabrication/manufacturing/laser-cutter.md
      - File Types:
          - Drawing Exchange Format (DXF): fabrication/file-types/dxf.md
  - Business:
    - Overview: business/overview.md
    - Branding: business/branding.md
    - Tools:
      - Overview: business/tools/tools.md
    - Fundraising:
      - Grants: business/fundraising/grants.md
      - Donations: business/fundraising/donations.md
    - Spending:
      - Stores: business/spending/stores.md
    - Communication:
      - Emails: business/communication/emails.md


theme:
  name: material
  logo: assets/logo_512.png
  favicon: assets/favicon.ico
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - navigation.expand
    - toc.follow
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
    - navigation.footer
    - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - glightbox
  - offline
  - git-revision-date-localized
  - git-authors:
      show_contribution: true
      exclude:
        - index.md
  - social:
      enabled: !ENV [CI, false]

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.keys
  - pymdownx.superfences:
     custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true


extra:
  analytics:
    provider: custom

extra_javascript:
  - javascripts/katex.js
  - javascripts/kotlin.js
  - https://unpkg.com/kotlin-playground@1
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/kotlin.css
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
