name: Build Documentation
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pipenv
      - name: Install pipenv
        run: |
          python -m pip install pipenv
      - name: Install dependencies
        run: pipenv sync
      - run: pipenv run mkdocs build