name: Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: pipenv
      - run: python3 -m pip install --upgrade pip pipenv
      - run: pipenv sync
      - run: pipenv run mkdocs gh-deploy --force
